[package]
name = "dfs"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3"
petgraph = "0.5"
wasm-bindgen = "0.2.67"
